#!/bin/sh

usage () {
	echo "Usage : $0 SOLVER"
	exit 1
}

if [[ $# -ne 1 ]]; then
	usage
fi

output_stat_file=./stats/$1.stats

for instance in $(ls -1 ./instances); do
	if [[ $instance != "README.md" ]]; then
		line=$(./runmain $1 $instance | grep $instance)
		echo $line >> $output_stat_file
		echo "> $instance <"
	fi
done

