#!/bin/sh


usage () {
	echo "Usage:"
	echo -e "\t./runmain SOLVER INSTANCE : Basically doing 'java -jar build/libs/JSP.jar --solver SOLVER --instance INSTANCE'"
	echo -e "\t./runmain -b SOLVER INSTANCE : ('gradle build' and 'gradle jar' is performed before running the program)"
	exit 1
}

build () {

	gradle build || exit 1
	gradle jar || exit 1
}

run () {
	java -jar build/libs/JSP.jar --solver $solver --instance $instance
}

if [[ $# -lt 2 ]]; then
	usage
fi

solver=$1
instance=$2

if [[ $# -eq 3 ]]; then
	if [[ $1 == "-b" ]]; then
		build
		solver=$2
		instance=$3	
	else
		usage
	fi
fi

run || (build && run)
