#!/bin/sh

if [[ $# -ne 1 ]]; then
	echo "Usage: ./test your.package.TestClass"
	echo "e.g. ./test jobshop.encodings.EncodingTests"
	exit 1
fi

set -x

gradle test --info > /dev/null

gradle test --tests $1 || exit 1

firefox	./build/reports/tests/test/index.html

