#!/bin/sh

out=index.html
colors=( "beautiblue" "red" "pink" "black" "blue" "green" "orange" "yellow" "grey" "purple" "greenish" "magenta" "brown" "dark_blue" "dark_red" "dark_grey" "dark_green" "beige")

make_dataset () {

	echo "> $3 <"
	label=$3

	(
		echo "label: '$label',"
		echo "backgroundColor: window.chartColors.$2,"
		echo "borderColor: window.chartColors.$2,"
		echo "data: ["
	) >> $out

	firsttime="1"

	for percentage in $(cat $1 | awk -c "{ print \$${4} }"); do

		if [[ $firsttime != "1" ]]; then
			echo -n ", " >> $out
		fi

		echo -n "'$percentage'" >> $out

		firsttime=$(echo "0")
	done

	(
		echo "],"
		echo "fill: false,"
	) >> $out
}

pre () {

	cat ./pre.html > $out

	(
		echo "var config = {"
		echo "type: 	'line',"
		echo "data:	{"
		echo -n "labels: ["
	) >> $out

	firsttime="1"
	# Take the first stat file and get all the instances that have worked
	for instance in $(echo ../`ls -1 ../ | grep -E "*.stats" | head -n 1` | xargs cat | awk -c '{ print $1 }'); do
		if [[ $instance != "README.md" ]]; then
			if [[ $firsttime != "1" ]]; then
				echo -n ", " >> $out
			fi
			echo -n "'$instance'" >> $out
			firsttime=$(echo "0")
		fi
	done

	(
		echo "],"
		echo "datasets: ["
	) >> $out
}

post() {
	(
		echo "]},"
	) >> $out

	cat $1 >> $out
}

parse_solvers_stats () {

	pre

	firsttime="1"
	colorindex=0

	for solver in $(ls -1 ../ | grep ".stats"); do
		if [[ $firsttime != "1" ]]; then
			echo -n ", " >> $out
		fi

		echo "{" >> $out
		make_dataset  "../$solver" ${colors[$colorindex]} $(echo -n "$solver" | sed -r "s/(.+).stats$/\1/g" | tr '[:lower:]' '[:upper:]') $1
		echo "}" >> $out

		colorindex=$(expr $colorindex + 1)
		firsttime=$(echo "0")
	done

	post $2
}

parse_best_makespan_only () {

	pre

	colorindex=0

	# Just take the first solver stats we find,
	# since the best makespan is common to all the solvers stats
	solver=$(ls -1 ../ | grep ".stats" | head -n 1)

	echo "{" >> $out
	make_dataset "../$solver" ${colors[$colorindex]} "Best Makespan" $1
	echo "}" >> $out

	post $2
}

stats="6"

if [[ $# -eq 0 ]]; then
	echo "Please tell me whether you want the runtime or distance statistics"
fi

case $1 in
	"best")
		stats="3"
		parse_best_makespan_only $stats "./post_best_makespan.html"
		;;
	"runtime")
		stats="4"
		parse_solvers_stats $stats "./post_runtime.html"
		;;
	"makespan")
		stats="5"
		parse_solvers_stats $stats "./post_makespan.html"
		;;
	"distance")
		stats="6"
		parse_solvers_stats $stats "./post_distance.html"
		;;
	*)
		stats="6"
		parse_solvers_stats $stats "./post_distance.html"
		;;
esac


firefox $out

